# Username for maven repository
vault_maven_repository_username: #if($mavenRepositoryUser!='__not_set__')${mavenRepositoryUser}#end

# Password for maven repository
vault_maven_repository_password: #if($mavenRepositoryPassword!='__not_set__')${mavenRepositoryPassword}#end

# Master password for Maven Password Encryption
## --- Generate a random maven master password (use a UUID) ---
#set( $str = "" )
#set( $randomUUID = $str.getClass().forName("java.util.UUID").getMethod("randomUUID") )
#set( $uuid = $randomUUID.invoke(null) )
vault_controlhost_maven_master_password: ${uuid}

# Password for AEM "admin" user and felix console
vault_aem_admin_password: ${aemAdminPassword}
