# Role that combines all application roles and configuration that is common for all environments

inherits:
- role: ${projectName}-aem-cms

variants:
- variant: aem-author
- variant: aem-publish


config:
  contentPackage.group: ${projectName}
  crypto:
#if ($optionAnsible=="y")
    # URLs of crypto keys to be deployed to AEM (as bundle files)
    aesCryptoKeyUrl: classpath:/crypto/master
    hmacCryptoKeyUrl: classpath:/crypto/hmac
#end