# Build validation

name: Build

on:
  push:
    branches-ignore:
      - master
      - experimental/**
  pull_request:
    branches-ignore:
      - master
      - experimental/**
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [11, 17]
        os: [ubuntu-latest]
        distribution: [temurin]
        include:
          - java: 11
            os: windows-latest
            distribution: temurin
          - java: 11
            os: macos-latest
            distribution: temurin

    steps:
      # Check out Git repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up environment with Java and Maven
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'maven'

      # Build & verify
      - name: Build and verify
        run: ./mvnw -s ./.maven-settings.xml -Pcontinuous-integration -B -U -D"archetype.test.settingsFile=./.maven-settings.xml" -D"groovy.grape.report.downloads=true" clean verify
